// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calc.proto

package calcpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	TaskId               int32    `protobuf:"varint,1,opt,name=Task_id,json=TaskId,proto3" json:"Task_id,omitempty"`
	TaskName             string   `protobuf:"bytes,2,opt,name=Task_name,json=TaskName,proto3" json:"Task_name,omitempty"`
	Duration             int32    `protobuf:"varint,3,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Resource             int32    `protobuf:"varint,4,opt,name=Resource,proto3" json:"Resource,omitempty"`
	PrevWork             string   `protobuf:"bytes,5,opt,name=Prev_work,json=PrevWork,proto3" json:"Prev_work,omitempty"`
	OrderId              int32    `protobuf:"varint,6,opt,name=Order_id,json=OrderId,proto3" json:"Order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b9900dc883ea68, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetTaskId() int32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *Request) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *Request) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Request) GetResource() int32 {
	if m != nil {
		return m.Resource
	}
	return 0
}

func (m *Request) GetPrevWork() string {
	if m != nil {
		return m.PrevWork
	}
	return ""
}

func (m *Request) GetOrderId() int32 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type RequestQuery struct {
	Requests             []*Request `protobuf:"bytes,1,rep,name=Requests,proto3" json:"Requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RequestQuery) Reset()         { *m = RequestQuery{} }
func (m *RequestQuery) String() string { return proto.CompactTextString(m) }
func (*RequestQuery) ProtoMessage()    {}
func (*RequestQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b9900dc883ea68, []int{1}
}

func (m *RequestQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestQuery.Unmarshal(m, b)
}
func (m *RequestQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestQuery.Marshal(b, m, deterministic)
}
func (m *RequestQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestQuery.Merge(m, src)
}
func (m *RequestQuery) XXX_Size() int {
	return xxx_messageInfo_RequestQuery.Size(m)
}
func (m *RequestQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestQuery.DiscardUnknown(m)
}

var xxx_messageInfo_RequestQuery proto.InternalMessageInfo

func (m *RequestQuery) GetRequests() []*Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

type Response struct {
	Message              int32    `protobuf:"varint,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b9900dc883ea68, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessage() int32 {
	if m != nil {
		return m.Message
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "grpCalc.Request")
	proto.RegisterType((*RequestQuery)(nil), "grpCalc.RequestQuery")
	proto.RegisterType((*Response)(nil), "grpCalc.Response")
}

func init() {
	proto.RegisterFile("calc.proto", fileDescriptor_a2b9900dc883ea68)
}

var fileDescriptor_a2b9900dc883ea68 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbd, 0x4b, 0xc4, 0x40,
	0x10, 0xc5, 0x8d, 0xf7, 0x91, 0xdc, 0x68, 0xa1, 0x0b, 0xe2, 0x7a, 0x36, 0x21, 0x58, 0xa4, 0x90,
	0x08, 0xb1, 0xb5, 0x10, 0xb5, 0xb9, 0xc6, 0x8f, 0x20, 0x08, 0x36, 0xc7, 0x5e, 0x32, 0x1c, 0x47,
	0x3e, 0x36, 0xce, 0x66, 0x15, 0xff, 0x2a, 0xff, 0x45, 0x99, 0x4d, 0xee, 0x10, 0xcb, 0xdf, 0xbc,
	0x7d, 0x6f, 0xdf, 0x0c, 0x40, 0xae, 0xaa, 0x3c, 0x69, 0x49, 0x77, 0x5a, 0xf8, 0x6b, 0x6a, 0xef,
	0x55, 0x95, 0x47, 0x3f, 0x1e, 0xf8, 0x19, 0x7e, 0x58, 0x34, 0x9d, 0x38, 0x05, 0xff, 0x55, 0x99,
	0x72, 0xb9, 0x29, 0xa4, 0x17, 0x7a, 0xf1, 0x24, 0x9b, 0x32, 0x2e, 0x0a, 0x71, 0x0e, 0x33, 0x27,
	0x34, 0xaa, 0x46, 0xb9, 0x1f, 0x7a, 0xf1, 0x2c, 0x0b, 0x78, 0xf0, 0xa8, 0x6a, 0x14, 0x73, 0x08,
	0x1e, 0x2c, 0xa9, 0x6e, 0xa3, 0x1b, 0x39, 0x72, 0xb6, 0x1d, 0xb3, 0x96, 0xa1, 0xd1, 0x96, 0x72,
	0x94, 0xe3, 0x5e, 0xdb, 0x32, 0x87, 0x3e, 0x13, 0x7e, 0x2e, 0xbf, 0x34, 0x95, 0x72, 0xd2, 0x87,
	0xf2, 0xe0, 0x4d, 0x53, 0x29, 0xce, 0x20, 0x78, 0xa2, 0x02, 0x89, 0xbb, 0x4c, 0x9d, 0xd1, 0x77,
	0xbc, 0x28, 0xa2, 0x1b, 0x38, 0x1c, 0x0a, 0xbf, 0x58, 0xa4, 0x6f, 0x71, 0xc9, 0x7f, 0x38, 0x36,
	0xd2, 0x0b, 0x47, 0xf1, 0x41, 0x7a, 0x94, 0x0c, 0xdb, 0x25, 0x83, 0x90, 0xed, 0x5e, 0x44, 0x17,
	0xae, 0x51, 0xab, 0x1b, 0x83, 0x42, 0x82, 0x5f, 0xa3, 0x31, 0x6a, 0x8d, 0xc3, 0xbe, 0x5b, 0x4c,
	0x6f, 0x01, 0xd8, 0x6f, 0x2b, 0xd5, 0x69, 0x12, 0x29, 0x8c, 0x99, 0xc4, 0xc9, 0xff, 0x5c, 0x57,
	0x60, 0x7e, 0xfc, 0x67, 0xdc, 0x27, 0x47, 0x7b, 0x77, 0xf0, 0x1e, 0x24, 0x57, 0x7c, 0xf0, 0x76,
	0xb5, 0x9a, 0xba, 0x9b, 0x5f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x66, 0x55, 0x5a, 0x3a, 0x81,
	0x01, 0x00, 0x00,
}
